sudo: required

language: python

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d postgres

script:
  - docker-compose run --rm --entrypoint "pytest tests" web

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t jstutters/colournaming .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jstutters/colournaming;
    fi
