version: '2'
services:
    web:
        build: .
        ports:
        - "5000:5000"
        volumes:
        - .:/app
        environment:
        - COLOURNAMING_CFG=/app/docker.cfg
        - FLASK_DEBUG=1
        command: run -h 0.0.0.0 -p 5000
    postgres:
        image: "postgres"
        ports:
        - "5432:5432"
        environment:
        - POSTGRES_PASSWORD=testpass
