version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
      
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: build container
          command: |
            docker-compose build
            docker-compose up -d postgres

      - run:
          name: run tests
          command: |
            docker-compose run --rm web test

      - store_artifacts:
          path: test-reports
          destination: test-reports
          